language: ruby
rvm:
  - 1.9.3
  - 2.1.1
#  - jruby-19mode
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
services:
  - mongodb
  - elasticsearch
before_script:
  - sleep 15