language: ruby
cache: bundler
#sudo: false
rvm:
  - 1.9.3
  - 2.1.1
#  - jruby-19mode
script: bundle exec rspec spec
branches:
  only:
    - master
services:
  - mongodb
  - elasticsearch
before_script:
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/2.4.1
  - sudo service elasticsearch restart
  - sleep 15