language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9.3
  - 2.1.1
#  - jruby-19mode
script: bundle exec rspec spec
branches:
  only:
    - master
services:
  - mongodb
  - elasticsearch
before_script:
  - sleep 15