production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] || 'mongodb://localhost' %>
development:
  sessions:
    default:
      database: ladder_development
      hosts:
        - localhost:27017
  options:
test:
  sessions:
    default:
      database: ladder_test
      hosts:
        - localhost:27017
options:
  scope_overwrite_exception: true
  skip_version_check: true
  identity_map_enabled: true
