require 'embedded/bibo'
require 'embedded/dbpedia'
require 'embedded/dcterms'
require 'embedded/foaf'
require 'embedded/prism'
require 'embedded/rdfs'
require 'embedded/skos'
require 'embedded/vcard'
